# Change these first
owner: juancarrillof # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: juanca.org
    url: https://www.juanca.org
  - name: changelog.juanca.org
    url: https://changelog.juanca.org

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.juanca.org
  # baseUrl: /your-repo-name
  logoUrl: https://www.juanca.org/content/images/2022/02/circle-icon.png 
  name: Status | juanca.org
  introTitle: "Welcome to the service status site for **juanca.org!**"
  introMessage: Below you'll find the live status of all services related to juanca.org.
  navbar:
    - title: juanca.org
      href: https://www.juanca.org 
    - title: GitHub repository
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
